### PR TITLE
Add test runner

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
Some users wants to use `test function`, I just add this one.

```js
// test/some/func.js
const test = require('eater/runner').test;
const assert = require('power-assert');

test('foo', (resolve, reject) => {
  assert(alice == bob);
  resolve();
});

test('bar', (resolve, reject) => {
  assert(alice !== bob); // fail here
  resolve();
});

test('buz', (resolve, reject) => {
  assert(alice !== bob);
  if (alwaysTrue) {
    resolve('pass'):
  }
  reject('should not be reached here');
});

```

```
Test Name: foo
  ✓ success foo
  ✗ failure bar
  ✓ success buz
✓ test/some/func.js
```

### CODE REVIEW

**Comment by yosuke-furukawa** [comment]
- [ ] need more test
- [ ] write docs
- [ ] introduce usecase 
- [ ] must-call is dependencies? or devDeps?

**Comment by twada** [comment]
Just out of curiosity, how and when to use `resolve` and `reject` arguments?

**Comment by yosuke-furukawa** [comment]
@twada 

`resolve` function is similar to `done` function in `mocha`. if this function is called, the test will pass regardless of sync/async test.

if you want to fail your test intentionally, call `reject` func, like assert.fail. Of course if you use `assert.fail`, you don't need to use `reject` function, but my test runner does not have `built-in assert` function, so I add `reject` argument.

**Comment by yosuke-furukawa** [comment]
add samples in PR comment.

**Comment by twada** [comment]
Thanks! That clears things up a lot 😃

**Pull request merged**
